use_frameworks!

target 'BlockCypherSwift_Example' do
  pod 'BlockCypherSwift', :path => '../'
  pod 'Anchorage'
  pod 'Result'
  pod 'QRCode'
  pod 'Realm'
  pod 'RealmSwift'
  pod 'lottie-ios'

  target 'BlockCypherSwift_Tests' do
    inherit! :search_paths

    
  end
end
